### ISSUE TITLE
Switch to Promises

### ISSUE THREAD

**Issue by aero31aero** [tldr-pages/tldr-node-client#160]
## Expected behaviour
The client should use promises instead of callbacks.

## Actual behaviour
The client uses callbacks predominantly.

## Further details

This is a placeholder issue for the task of switching to Promises. I'd like to suggest using Bluebird Promises for the migration, at least, mainly because of the following function(and its usage):

```js
const Promise = require('bluebird');
const fs = Promise.promisifyAll(require('fs-extra'));
fs.readFileAsync(file).then(data => {
  console.log(data.toString());
}).catch(error => {
  console.error(error);
});
```

This would allow easy and fast migration to promises.

## Progress

- [ ] cache.js
- [x] config.js (not applicable)
- [x] index.js
- [x] messages.js (not applicable)
- [x] parser.js (not applicable)
- [x] platform.js (not applicable)
- [x] remote.js
- [x] render.js (not applicable)
- [x] search.js
- [x] theme.js (not applicable)
- [ ] tldr.js
- [x] utils.js (not applicable)

**Comment by agnivade** [comment]
I am okay with switching to promises to avoid the callback depth. Although its not too much in our case. But please use the native Promise in node. No need to add any new dependency.

**Comment by vladimyr** [comment]
Would you let me to help you with this one? :wink:

Before I dive into technical stuff, let me say few things:

1. I'm longtime (almost on daily basis) happy `tldr-node-client` user, **giant** kudos to all of you who put in your work and effort to make it happen :+1: :100: :trophy:
2. I'm not here to give anyone condescending-ish _programming lessons_ period. I'm sort of jumping straight out of nowhere and doing late _code review_ which is unfortunate by definition but my only motive is giving back to this **wonderful** :heart: project by offering my help. I did write small essay down there but purely to support my case. I hope you'll find it constructive and I honestly hope that by writing this I'm avoiding any unfortunate misinterpretations of my act.
3. I basically rewrote whole article but still it is always good to bring more material into discussion so here you go:
https://hackernoon.com/javascript-promises-best-practices-anti-patterns-b32309f65551
In the same time I want to **strongly** emphasize that what I found inside codebase is light years ahead compared to bad code example from the article.

Back to topic...
There are some recent commits on master branch that bring in required changes. Went through code and noticed particular pattern. Promisification is done by essentially wrapping methods with `new Promise(...)` calls which is fine but those already contained promise chains so now we ended up with nested promise chains, sort of inception thingie :dizzy_face:

Let me show you what I'm talking about using following code example:
https://github.com/tldr-pages/tldr-node-client/blob/b7491a0b9c03b803af59ca32500c8de740805aab/lib/index.js#L116-L130

What we have here is method that either resolves with loaded index or invokes `#readShortPagesIndex` which would eventually load it and _return_. That invocation already returns promise instance so it can be simply returned to caller by doing following:

```js
function getShortIndex() {
  if (shortIndex) {
    return shortIndex;
  } else {
    return readShortPagesIndex();
  }
}
```

However this won't work in cases we already have loaded index because `shortIndex` is not a Promise instance. It is an object, meaning it does not have `.then` method and can't be used as return value. What is actually needed is promise that would resolve with it. Creating promise instances from values is quite simple and can be done in following way:

```js
function getShortIndex() {
  if (shortIndex) {
    return Promise.resolve(shortIndex);
  } else {
    return readShortPagesIndex();
  }
}
```

Now both conditional branches return promise instance and method is successfully promisified :rocket: For sake of trimming it down even more we could leverage this early `return` and completely omit `else` block:

```js
function getShortIndex() {
  if (shortIndex) {
    return Promise.resolve(shortIndex);
  }
  return readShortPagesIndex();
}
```

Now take a moment and compare it to starting point. I'm well aware that using LOC as code quality indicator is wrong by definition but I also believe that we ended up with code that is both easier to read and grasp :wink:

I took initiative and completed this unwrapping exercise using my own fork, here is what I got:
https://github.com/vladimyr/tldr-node-client/commit/a7b3d2c8456ab4eda4885afcceca30951e4070f7

`2 changed files with 64 additions and 129 deletions.`
I would say that is quite good score :smile:

That's it. If you are interested in getting it merged just let me know and I'll gladly and promptly create PR for it :smile:
Also, if you have any additional questions or thoughts feel free to ask, I'll be glad and honored to help you :wink: :+1:

**Comment by agnivade** [comment]
Perfect. I knew my promise-foo was sub-par. Promise chains _always_ trip me up. A PR will be most welcome !

**Comment by agnivade** [comment]
Done with #199
