### ISSUE TITLE
Response time needs to improve

### ISSUE THREAD

**Issue by gpenghe** [tldr-pages/tldr-node-client#234]
## Expected behaviour
Node.js application might be slower than C/C++. It might even be slower than Python. But is it normal to be 7 times slower than the Python client, and 70 times slower than C?

## Actual behaviour
When I query a page, the response time is typically 700 ms in my old Macbook Air (about 400 ms on my Linux PC). In comparison, querying the same page with the current Python client uses 10 ms on the same MBA, and 1ms (!) with the C client.

The query time is slower for the first query, and relatively consistent in the subsequent queries. The time numbers mentioned above reference those subsequence numbers.

In everyday use, the difference is noticeable. The C version feels very snappy. The Python client has a noticeable delay. And the node client has a very noticeable delay.

## Log, debug output
```bash
➜  tldr-node-client git:(master) ✗ time ./bin/tldr shellcheck
[...]
./bin/tldr shellcheck  0.72s user 0.12s system 113% cpu 0.744 total

➜  tldr-node-client git:(master) ✗ cd ../tldr-python-client
➜  tldr-python-client git:(master) time ./tldr.py shellcheck
[...]
./tldr.py shellcheck  0.10s user 0.11s system 70% cpu 0.295 total

➜  tldr-python-client git:(master) cd ../tldr-c-client
➜  tldr-c-client git:(master) time ./tldr shellcheck
[...]
./tldr shellcheck  0.01s user 0.01s system 64% cpu 0.032 total
```
## Environment
- Operating system - OSX High Sierra 10.13.6
- NodeJS version: 10.7.0

**Comment by gpenghe** [comment]
The Rust client has some interesting tests 5 months ago (https://github.com/dbrgn/tealdeer/blob/master/README.md). His test shows Node client and Python client has similar invocation time. Not sure why my result is different...

| Client | Times (ms) | Avg of 5 (ms) |
| --- | --- | --- |
| [Tealdeer](https://github.com/dbrgn/tealdeer/) | `15/11/5/5/11` | `9.4` |
| [C client](https://github.com/tldr-pages/tldr-cpp-client) | `11/5/12/11/15` | `10.8` |
| [Bash client](https://github.com/pepa65/tldr-bash-client) | `15/19/22/25/24` | `21.0` |
| [Go client by k3mist](https://github.com/k3mist/tldr/) | `98/96/100/95/101` | `98.8` |
| [Python client](https://github.com/lord63/tldr.py) | `152/148/151/158/140` | `149.8` |
| [NodeJS client](https://github.com/tldr-pages/tldr-node-client) | `169/171/170/170/170` | `170.0` |

**Comment by agnivade** [comment]
I have seen the issue only when the index.json is not in the buffer cache when you are running tldr for the first time. After that, it is reasonably fast for me.

```
time tldr shellcheck
...
real	0m0.395s
user	0m0.460s
sys	0m0.016s
```

There might be scope for improvement of course. I haven't really looked into optimizing performance as I didn't feel any need. But please do feel free to investigate and send PRs !

**Comment by rodrigograca31** [comment]
I also noticed this as of 2020.

Here are my findings:

`const Tldr = require('../lib/tldr');` takes: 257.681ms to load

because depends on:
`const Cache = require('./cache');` takes 118.835ms to load
and 
`const search = require('./search');` takes 75.350ms to load

`lib/cache.js` depends on `lib/remote.js` which depends on `request`
`let request = require('request');` which is the main slow module being used and takes 115.277ms to load

`lib/search.js` depends on `natural` that takes 74.807ms to load and is basically the second slowest module.

P.S. I'm only pointing out the slowest dependencies, not all of them.

--- 

That said, to solve the main slowness we should remove/replace `request`. (and `node-unzip-2` is also slow!)
In case you don't know [request has been deprectaed](https://github.com/request/request/issues/3142)

[Here is a list of alternative packages we can use](https://github.com/request/request/issues/3143), I would use `axios` because its well known and seems to support proxies which are needed.

I'm not 100% comfortable changing this code but maybe someone here is, and could make the switch from `request` to `axios`.
but I noticed that only by moving `let request = require('request');` to inside the function `download` is already a huge improvement!!!

Not sure this is the best approach but by moving `require` of `node-unzip-2` and `request` to inside the function and the same for `natural` we literally go from 300ms to 170ms (half?) which feels instant!

**Comment by rodrigograca31** [comment]
Alternatively we can configure this project to use `browserify` [like this other project I maintain does](https://github.com/streamich/git-cz/blob/master/package.json)... 
maybe there's a better tool? 🤔 because looks like `browserify` is more for making a single bundle for the browser...? 🤔
can we use webpack? 

The following command: `browserify --node -o temp.js bin/tldr` outputs an error. which can temporarily ignore by removing the requirement and use of the `natural` package. of course this isn't correct to do but allows us to create the `temp.js` file in order to test `time node temp.js tldr` and see :eyes: the huge difference in performance! once again it feels instant!

**Comment by agnivade** [comment]
Thank you @rodrigograca31 for investigating this!

It's good to replace `request` with a newer altnernative, but I would like to understand what is it about request that is making things slow and how is it faster with an alternative? Can you explain that? 

> Not sure this is the best approach but by moving require of node-unzip-2 and request to inside the function and the same for natural we literally go from 300ms to 170ms (half?) which feels instant!

I am not a Node.js expert but I would like to understand why this happens? Do you know? Without a proper explanation, it would not be right to make those changes.

That said, coming to choosing a new alternative, I myself quite like [got](https://github.com/sindresorhus/got). Axios is also great; I have used it in the past. But it's useful to maintain a single API across browsers and Node both. In our case, we don't need browser support, only Node support is sufficient.

In that regard, I think a library which has fewer things to maintain, like `got`, might be better suitable as a replacement I think.

**Comment by rodrigograca31** [comment]
> It's good to replace request with a newer altnernative, but I would like to understand what is it about request that is making things slow and how is it faster with an alternative? Can you explain that?

[It's just the way `request` is. It self depends on lots of things which make it slow when you require it](https://github.com/request/request/issues/2261)
As the last comments says:
This is a general dependency issue. We have a lot of them, they are big. It's known.

>> Not sure this is the best approach but by moving require of node-unzip-2 and request to inside the function and the same for natural we literally go from 300ms to 170ms (half?) which feels instant!

> I am not a Node.js expert but I would like to understand why this happens? Do you know? Without a proper explanation, it would not be right to make those changes.
I know why it does happen I just don't know why people don't make it the more performance way...
Lets do the following scenario:
```javascript
const mod1 = require("mod1")
const mod2 = require("mod2")

const func1 = () => {
    mod1.something()
}
const func2 = () => {
    mod2.something()
}
func2() //executes only func2!
```
this code will always require the 2 other modules wether you use them or not.
my suggestion would be something like:
```javascript
const func1 = () => {
    const mod1 = require("mod1")
    mod1.something()
}
const func2 = () => {
    const mod2 = require("mod2")
    mod2.something()
}
func2() //executes only func2!
```
This will save on initial loading time because only when you actually call/use `func2` it requires `mod2` and uses it.
Usually, it's done using the first approach to organize code better and because you might want to use `mod2` in both functions and you don't want to repeat `const mod2 = require("mod2")` in both. 

This will trade initial loading time for "later down the line" time, meaning if you never run a bunch of functions why do you load the code for them first? 🤔
Other than that I'm not sure if there are other drawbacks of only including the code when you need it since I see everyone doing the first approach... maybe I don't have enough knowledge or maybe everyone does it that way because it's easier and faster...

Just to clarify: I've not done this optimization on my PR. I kept the loading of the modules as it was but changed from `request` to `axios` to improve loading performance.

I chose `axios` over `got` (and the others) because of 2 main things:
 - smaller, smaller loading time: `axios: 20.296ms, got: 28.132ms`
 - support for `http_proxy` out of the box

P.S. from what I understood the code for the proxy wasn't(isn't) even working. Doesn't use `.get()` when setting the defaults... 🤔

I hope I explained my self thoroughly, feel free to ask any further questions.

**Comment by agnivade** [comment]
Ok, so it's the time to require. ~~But doesn't Node.js requires modules only once in the lifetime of the program?~~ Ahh but of course, a CLI tool is only run once, during which Node.js has to do all of its stuff. Thanks for the clarification there.

Yeah, the part of requiring modules inside functions is normally not relevant for long-running programs because I guess it's only a startup cost. But I could see how they matter for CLI tools like these.

Ok, now coming to axios vs got - got also supports proxying, although not out of the box. So using axios does make sense there. Regarding the load time, can we do 10 runs for both axios and got, and look at the median and mean value for both?

I am leaning towards axios here, but I'd like to get some thorough numbers done so that our change is backed by solid research. Thank you for your time!

**Comment by rodrigograca31** [comment]
Sure!

Not sure how to benchmark it because if you do a for loop with requires they actually get cached and take less than 1 millisecond to load the second time, so here is the benchmark I did:
```javascript
console.time("axios");
const axios = require("axios");
console.timeEnd("axios");

console.time("got");
const got = require("got");
console.timeEnd("got");
```
save it as `axios_got.js` and run this on your shell:
`for i in {1..10}; do node axios_got.js; done`

you will get a similar result:
```bash
axios: 21.512ms
got: 29.289ms
axios: 20.784ms
got: 28.477ms
axios: 20.009ms
got: 28.518ms
axios: 20.362ms
got: 29.071ms
axios: 20.304ms
got: 28.149ms
axios: 21.138ms
got: 27.634ms
axios: 22.068ms
got: 28.440ms
axios: 20.617ms
got: 28.363ms
axios: 21.480ms
got: 28.890ms
axios: 21.280ms
got: 27.718ms
```
as you can see `got` always takes more time. you might ask: can that be because its the second required?
that's actually a really good question because you invert the order this is the output:
```bash
got: 44.352ms
axios: 8.348ms
got: 41.262ms
axios: 7.470ms
got: 40.370ms
axios: 8.506ms
got: 41.511ms
axios: 8.676ms
got: 41.852ms
axios: 8.160ms
got: 49.689ms
axios: 7.220ms
got: 42.140ms
axios: 7.540ms
got: 40.542ms
axios: 7.394ms
got: 39.836ms
axios: 7.359ms
got: 42.255ms
axios: 7.092ms
```
Way worst.... not sure why🤔

Let me know if my "benchmark" is biased in some way 😅 maybe run it too?

P.S. You got a good point that a CLI tool is not like other NodeJS projects and maybe should not require everything upfront. We should discuss moving all `require` later on.

**Comment by agnivade** [comment]
I would guess it is because of the transitive dependencies getting cached after got or axios gets loaded. A better way would be to run them individually. Then you can compare apples-apples.

```
got: 40.353ms
got: 40.298ms
got: 40.403ms
got: 40.386ms
got: 40.756ms
got: 39.814ms
got: 40.172ms
got: 41.072ms
got: 41.486ms
got: 39.846ms

axios: 24.189ms
axios: 20.294ms
axios: 18.462ms
axios: 20.58ms
axios: 18.545ms
axios: 20.887ms
axios: 18.651ms
axios: 20.822ms
axios: 18.229ms
axios: 20.413ms
```

Thanks for your time @rodrigograca31 ! I think we can move ahead with the review now.

**Comment by agnivade** [comment]
Closing this now as we have landed a PR that replaces request by axios. Thanks @rodrigograca31 !

**Comment by rodrigograca31** [comment]
Nice! 

Awesome that I was able to contribute and increase the speed! :heart: 

And @agnivade asked great and very thoughtful questions!
