### ISSUE TITLE
tldr is showing a debug message when a page was not found

### ISSUE THREAD

**Issue by marchersimon** [tldr-pages/tldr-node-client#335]
When I run tldr on a command which could not be found, I get the following output:
```
✔ Page not found. Updating cache...
✔ Creating index...
Error: Page not found.
If you want to contribute it, feel free to send a pull request to: https://github.com/tldr-pages/tldr
    at /usr/lib/node_modules/tldr/lib/tldr.js:147:17
```
Does the last line have any purpose? It's always the same and not really useful.
(tldr version 3.3.7)

**Comment by vladimyr** [comment]
> Does the last line have any purpose? It's always the same and not really useful.

That is definitely unwanted. Feel free to open PR to remove it.

**Comment by marchersimon** [comment]
I'd like to, but i hardly know any javascript.

**Comment by vladimyr** [comment]
Let me decipher that for you.

```
Error: Page not found.
If you want to contribute it, feel free to send a pull request to: https://github.com/tldr-pages/tldr
```
is just a multiline error message as seen here: https://github.com/tldr-pages/tldr-node-client/blob/7e49dda42a11dfc07b5547b1bc9a20bc334b8792/lib/messages.js#L9-L12

```
    at /usr/lib/node_modules/tldr/lib/tldr.js:147:17
```
part is called stack trace and tells you where the error originates from. In this case, it has been thrown from https://github.com/tldr-pages/tldr-node-client/blob/7e49dda42a11dfc07b5547b1bc9a20bc334b8792/lib/tldr.js#L147

Finally, all propagated errors are being caught using central error handler: https://github.com/tldr-pages/tldr-node-client/blob/7e49dda42a11dfc07b5547b1bc9a20bc334b8792/bin/tldr#L121-L124
And if you change that `console.error(err)` to `console.error(err.message)` you'll lose the stack trace portion and get just a nice error message printed.

Unfortunately, that is not really the right way to solve it because there are two categories of errors that might happen during execution: those that are expected as this one, and those that are not. In the case of the latter, you very much need that stack trace so the end-user can include it as a part of their bug report.

**Comment by owenvoke** [comment]
Rather than the use of `throw new Error(messages.notFound());`, could we just use `console.error(messages.notFound())` with `process.exit(1)`?

**Comment by marchersimon** [comment]
Shouldn't we actually do the same for `messages.emptyCache()`?

**Comment by vladimyr** [comment]
> Rather than the use of `throw new Error(messages.notFound());`, could we just use `console.error(messages.notFound())` with `process.exit(1)`?

Depends do we want to make it work or to make it _right_. Exiting from various places inside the codebase makes it harder to reason about it and should be avoided if possible. Instead, the error should be propagated up and logged on top-level. But not a generic error, a subclass of it instead, i.e. `TldrError`.

**Comment by vladimyr** [comment]
> Shouldn't we actually do the same for `messages.emptyCache()`?

Absolutely!

**Comment by marchersimon** [comment]
How about
```javascript
class TldrError extends Error {
    constructor(message) {
        super(message);
    }
}
```
and
```javascript
p.catch((err) => {
    if(err instanceof TldrError) {
        console.error(err.message());
    } else {
        console.error(err);
    }
    process.exitCode = 1;
  });
```
?

**Comment by vladimyr** [comment]
> I'd like to, but i hardly know any javascript.

Oh really 😀

**Comment by marchersimon** [comment]
I just copy-pasted stuff from the internet :sweat_smile:

**Comment by vladimyr** [comment]
> I just copy-pasted stuff from the internet 😅

You did that by the book 😂
https://nitter.cc/ThePracticalDev/status/705825638851149824

**Comment by marchersimon** [comment]
Whereever I put the `TldrError` class I always get `ReferenceError: TldrError is not defined` at `err instanceof TldrError`

**Comment by bl-ue** [comment]
@marchersimon if you put the `TldrError` class in a file that's not the file your using it in, you'll need to:
1. Export it, from the file it's defined in 
2. Import it, from the file you're using it in

To export it, this will work: `module.exports.TldrError = TldrError`.

To import it, you can do this (somewhere at the top of the file): `const { TldrError } = require("file.js")`

**Comment by marchersimon** [comment]
@bl-ue I tried it in `tldr` and `lib/tldr.js` and I got the error both times. When I put it in a seperate file and export and import it, I still get the same error.

**Comment by marchersimon** [comment]
Exactly as you told:
`lib/tldrerror.js`:
```javascript
module.exports.TldrError = TldrError

class TldrError extends Error {
    constructor(message) {
        super(message);
    }
}
```
In `lib/tldr.js`:
```javascript
const TldrError = require('./tldrerror');
```
In `tldr`
```javascript
const TldrError = require('../lib/tldrerror');
```
I tried importing it with and without the curly braces.

Btw, thanks for explaining all that to me, you probably would be a lot faster if you did it yourself :sweat_smile:

**Comment by bl-ue** [comment]
No problem, I don't mind in the least.

1. It's more conventional (at least, it also may be required 🤷🏻) to export things after you declare them, so in `tldrerror.js` put the `module.exports` line below the class definition

2. Since you're creating a whole new file for `TldrError` (which is the right way to do it), and you're probably not going to put anything else than the class in the file, you can directly export the class instead of exporting an object that contains the class, so write `module.exports = TldrError;` instead

That should theoretically work.

**Comment by marchersimon** [comment]
Worked! Now it seems like `TldrError` doesn't have a function `message()`, which however did work with `Error`. Should't the function be inherited to `TldrError`?

**Comment by bl-ue** [comment]
It's a property, and it works for me:
```console
$ node
Welcome to Node.js v12.21.0.
Type ".help" for more information.
> class TldrError extends Error {
...     constructor(message) {
.....         super(message);
.....     }
... }
undefined
> e = new TldrError('asd')
TldrError: asd
    at REPL6:1:5
    at Script.runInThisContext (vm.js:120:18)
    at REPLServer.defaultEval (repl.js:442:29)
    at bound (domain.js:427:14)
    at REPLServer.runBound [as eval] (domain.js:440:12)
    at REPLServer.onLine (repl.js:777:10)
    at REPLServer.emit (events.js:326:22)
    at REPLServer.EventEmitter.emit (domain.js:483:12)
    at REPLServer.Interface._onLine (readline.js:329:10)
    at REPLServer.Interface._line (readline.js:658:8)
> e.message
'asd'
> 
```

**Comment by marchersimon** [comment]
It works!!! :tada: 
I wrote `message()`, instead of `message`. 
I'll open a PR
