### ISSUE TITLE
--render flag not outputting seemingly correctly formatted md page

### ISSUE THREAD

**Issue by ostera** [tldr-pages/tldr-node-client#62]
From this session, there's something going on with the rendering. The page itself might not be properly format (but it's perfectly usable on Github's editor: https://github.com/ostera/tldr/blob/8a624be47ae8af7b4056e55127b24c2944a02a28/pages/not-found.md)

```bash
$ tldr --version
1.4.0

$ cat ./pages/not-found.md

# Oops! :(

## Command Not Found

It seems the command you were looking for is not available yet.

Contributing is simple! All done from within Github. [Add this page](https://github.com/tldr-pages/tldr/new/master/pages)

Questions? [Read our Contributing guidelines](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md)

$ tldr --render ./pages/not-found.md

  Oops! :(


$
```

For cross reference, the `not-found` page is under discussion here: https://github.com/tldr-pages/tldr/pull/652

**Comment by igorshubovych** [comment]
Currently node client is rendering pages with [this format](https://github.com/tldr-pages/tldr/blob/master/CONTRIBUTING.md#markdown-format).

**Comment by ostera** [comment]
Why doesn't it print regular markdown?

**Comment by rprieto** [comment]
That's because it's not intended to be a Markdown renderer.

The `--render` flag actually calls the full `tldr` parsing/rendering routine, including extracting the list of examples, parsing the `{{}}` tokens, etc... It's mostly a helper tool for contributors, e.g.
- if you make a change to a given page like `cat.md` locally, you can check how the client will render it before even making a pull request
- if you make changes to the client itself (e.g. parsing logic, implementing themes...), you can use this to render specific "hand made" examples and corner cases, instead of doing `tldr cat` and having to modify the `cat` page to include your specific tests

Hope this makes sense. I like the idea of a nice `not found` message though... Just wondering if it  belongs with the pages, or if it's up to each client to implement (e.g. web links won't make any sense on the command line).

**Comment by rprieto** [comment]
Linking a related question: https://github.com/tldr-pages/tldr/pull/652
