### ISSUE TITLE
npm fails to install tldr

### ISSUE THREAD

**Issue by xingped** [tldr-pages/tldr-node-client#98]
## Expected behaviour
tldr should install from npm just fine

## Actual behaviour
`npm install -g tldr` fails with the output below

## Log, debug output
```
~ $ sudo npm install -g tldr
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/bin/tldr -> /usr/lib/node_modules/tldr/bin/tldr

> tldr@1.6.0 postinstall /usr/lib/node_modules/tldr
> node ./bin/tldr --update

Updating...
/usr/lib/node_modules/tldr/node_modules/wrench/lib/wrench.js:481
            throw err;
            ^

Error: EACCES: permission denied, mkdir '/home/xingped/.tldr'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at mkdirSyncRecursive (/usr/lib/node_modules/tldr/node_modules/wrench/lib/wrench.js:466:12)
    at Object.mkdirSyncRecursive (/usr/lib/node_modules/tldr/node_modules/wrench/lib/wrench.js:473:17)
    at /usr/lib/node_modules/tldr/lib/cache.js:55:12
    at Extract.<anonymous> (/usr/lib/node_modules/tldr/lib/remote.js:28:5)
    at emitNone (events.js:91:20)
    at Extract.emit (events.js:185:7)
    at DirWriter.<anonymous> (/usr/lib/node_modules/tldr/node_modules/unzip2/lib/extract.js:42:10)
    at emitNone (events.js:91:20)
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "tldr"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! tldr@1.6.0 postinstall: `node ./bin/tldr --update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tldr@1.6.0 postinstall script 'node ./bin/tldr --update'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tldr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/tldr --update
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tldr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tldr
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xingped/npm-debug.log
```

## Environment
- Operating system - Linux Mint 18
- NodeJS version - 6.5.0

**Comment by waldyrious** [comment]
@zdroid any hints on how to resolve this? I'd also like us to make a new release since https://github.com/tldr-pages/tldr-python-client/issues/7 is blocked on the theme support for the node client, which was introduced in https://github.com/tldr-pages/tldr-node-client/pull/61 (after the latest release, [1.6.0](https://github.com/tldr-pages/tldr-node-client/releases/tag/v1.6.0)).

**Comment by zdroid** [comment]
@waldyrious He just has to do the workaround from README (`npm install -g --ignore-scripts tldr &&
tldr --update`) and it'll be installed without errors.

About publishing new release: #101 is useful to be merged before new release is published, as it removes needless files from the package.

**Comment by waldyrious** [comment]
But shouldn't the errors not occur in the first place? Or is this an artifact of a previous installation, or...?

**Comment by zdroid** [comment]
@waldyrious It's an issue related to how npm scripts are executed, most likely Linux-only. I had the same issue when I tried to install tldr without the workaround.

**Comment by waldyrious** [comment]
I had it too when I tried to update tldr (was on 1.4.0), which failed, so I uninstalled and reinstalled. This was on OS X, so it's not even platform-specific. I don't think the regular npm installation command should fail and require a workaround.

**Comment by zdroid** [comment]
Agree. Maybe the issue is wrench.js-related, as the installation failed after it reached the wrench.js part? wrench.js is outdated anyway.

**Comment by agnivade** [comment]
I am working on a fix currently. Will send a PR soon.

**Comment by agnivade** [comment]
Sent #103.

The problem is not very easy to solve. Basically what we are trying to achieve here is execute a script after installation. Now everything works fine if you are doing it as non-root. But since its at a global level, usually everyone's `/usr/local/bin` is under root, therefore people will do `sudo npm install -g`. Now the problem with this is npm by default will downgrade the user permission for postinstall scripts to `nobody` when run as root. This is a problem for us because it does not allow to copy files under user's home directory.

There are a couple of solutions -
1. Do not use the postinstall step at all. So users will have to run 2 commands(`install` and `tldr --update`) to get started.
2. Pass `--unsafe-perm=true` in the installation step. This will use root permissions while installation which will make the `.tldr` directory as root. - Not good.
3. Pass the `--user=<username>` option which will let npm use that user while executing the postinstall script.

I went with the 3rd option as that seemed to be the most reasonable compromise to me.

P.S. - How was this even pushed in the first place without testing ? The solution mentioned in the README is a complete hack. The wording `if you are having problems` is untrue. It will **always** throw an error.

**Comment by waldyrious** [comment]
Nice analysis and explanation. I agree with the compromise you picked, seems to be the most reasonable one.

**Comment by agnivade** [comment]
README is fixed. Waiting for the patch to be published to npm.

**Comment by zdroid** [comment]
Well @agnivade, you can close the issue as it's fixed in latest version. It just has to be published.

**Comment by agnivade** [comment]
which is done now too !
